# Generated by Django 2.1.1 on 2018-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
